export const PRESETS = [
  {
    id: 'hormozi',
    name: 'Hormozi Impact',
    description: 'High-energy bold pop with yellow punch word highlight',
    badge: 'VIRAL',
    style: {
      fontFamily: 'Montserrat',
      fontSize: 34,
      fontWeight: '900',
      textTransform: 'uppercase',
      primaryColor: '#FFFFFF',
      activeColor: '#FFE600',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: '#000000',
      shadowBlur: 8,
      backgroundColor: 'transparent',
      backgroundPadding: 0,
      borderRadius: 0,
      positionY: 74,
      positionX: 50,
      animationType: 'pop',
      maxWordsPerSegment: 3
    }
  },
  {
    id: 'beast',
    name: 'MrBeast Explosive',
    description: 'Vibrant neon green bounce with heavy contrast',
    badge: 'POPULAR',
    style: {
      fontFamily: 'Russo One',
      fontSize: 36,
      fontWeight: '900',
      textTransform: 'uppercase',
      primaryColor: '#FFFFFF',
      activeColor: '#00FF66',
      strokeColor: '#000000',
      strokeWidth: 7,
      shadowColor: '#000000',
      shadowBlur: 10,
      backgroundColor: 'transparent',
      backgroundPadding: 0,
      borderRadius: 0,
      positionY: 72,
      positionX: 50,
      animationType: 'bounce',
      maxWordsPerSegment: 3
    }
  },
  {
    id: 'neon',
    name: 'Neon Cyberpunk',
    description: 'Glowing cyan electric karaoke flow',
    badge: 'AESTHETIC',
    style: {
      fontFamily: 'Outfit',
      fontSize: 32,
      fontWeight: '800',
      textTransform: 'uppercase',
      primaryColor: '#94A3B8',
      activeColor: '#00FFFF',
      strokeColor: '#030712',
      strokeWidth: 4,
      shadowColor: '#00FFFF',
      shadowBlur: 12,
      backgroundColor: 'transparent',
      backgroundPadding: 0,
      borderRadius: 0,
      positionY: 75,
      positionX: 50,
      animationType: 'karaoke',
      maxWordsPerSegment: 4
    }
  },
  {
    id: 'fire',
    name: 'Fire Flame',
    description: 'Hot red-orange gradient pop for hooks',
    badge: 'HIGH HOOK',
    style: {
      fontFamily: 'Bebas Neue',
      fontSize: 38,
      fontWeight: '700',
      textTransform: 'uppercase',
      primaryColor: '#FFFBEB',
      activeColor: '#FF3B30',
      strokeColor: '#450A0A',
      strokeWidth: 6,
      shadowColor: '#EA580C',
      shadowBlur: 10,
      backgroundColor: 'transparent',
      backgroundPadding: 0,
      borderRadius: 0,
      positionY: 70,
      positionX: 50,
      animationType: 'pop',
      maxWordsPerSegment: 2
    }
  },
  {
    id: 'minimal',
    name: 'Clean Frosted Pill',
    description: 'Minimalist subtitle bar with smooth blur backdrop',
    badge: 'ELEGANT',
    style: {
      fontFamily: 'Plus Jakarta Sans',
      fontSize: 24,
      fontWeight: '700',
      textTransform: 'none',
      primaryColor: '#F8FAFC',
      activeColor: '#38BDF8',
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: 'transparent',
      shadowBlur: 0,
      backgroundColor: 'rgba(15, 23, 42, 0.82)',
      backgroundPadding: 10,
      borderRadius: 14,
      positionY: 82,
      positionX: 50,
      animationType: 'fade',
      maxWordsPerSegment: 4
    }
  },
  {
    id: 'comic',
    name: 'Comic Marker',
    description: 'Hand-drawn marker style with pastel yellow pop',
    badge: 'CREATIVE',
    style: {
      fontFamily: 'Bangers',
      fontSize: 36,
      fontWeight: '400',
      textTransform: 'uppercase',
      primaryColor: '#FFFFFF',
      activeColor: '#FACC15',
      strokeColor: '#000000',
      strokeWidth: 6,
      shadowColor: '#000000',
      shadowBlur: 6,
      backgroundColor: 'transparent',
      backgroundPadding: 0,
      borderRadius: 0,
      positionY: 73,
      positionX: 50,
      animationType: 'bounce',
      maxWordsPerSegment: 3
    }
  }
];
